// <auto-generated />
namespace DataAccsesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_addAdminStatü : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_addAdminStatü));
        
        string IMigrationMetadata.Id
        {
            get { return "202209260726357_mig_addAdminStatü"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
